export const IconButton = <const>{
  EXCEL: 'fas fa-file-excel',
  WORD: 'fas fa-file-word',
  POWERPOINT: 'fas fa-file-powerpoint',
  PDF: 'fas fa-file-pdf',
  IMAGE: 'fas fa-image',
  VIDEO: 'fas fa-file-video',
  ADD: 'fas fa-plus',
  EDIT: 'fas fa-pencil-alt',
  DELETE: 'fas fa-trash',
  SEARCH: 'fas fa-search',
  CLEAR: 'fas fa-ban',
  CLOSE: 'fas fa-times',
  RESET: 'fas fa-undo',
  BACK: 'fas fa-chevron-left',
  SAVE: 'fas fa-check',
  SUBMIT: 'fas fa-check',
  LOCK: 'fas fa-lock',
  CALENDAR: 'fas fa-calendar',
  UPLOAD: 'fas fa-upload',
  CLOUDUPLOAD: 'fas fa-cloud-upload-alt',
  DOWNLOAD: 'fas fa-download',
  CLOUDDOWNLOAD: 'fas fa-cloud-download-alt',
  REMOVE: 'fas fa-times',
  VIEW: 'fas fa-info',
  UPDATE: 'fas fa-check',
  AUTHORIZE: 'fas fa-cog'
};
